/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedCarrinhoRouteImport } from './routes/_authenticated/carrinho'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPerfilIndexRouteImport } from './routes/_authenticated/perfil.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedPerfilLocacoesRouteImport } from './routes/_authenticated/perfil.locacoes'
import { Route as AuthenticatedPerfilEventosRouteImport } from './routes/_authenticated/perfil.eventos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminLocacoesRouteImport } from './routes/_authenticated/admin.locacoes'
import { Route as AuthenticatedAdminFavoritosRouteImport } from './routes/_authenticated/admin.favoritos'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminCatalogoRouteImport } from './routes/_authenticated/admin.catalogo'
import { Route as AuthenticatedAdminCalendarioRouteImport } from './routes/_authenticated/admin.calendario'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarrinhoRoute = AuthenticatedCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilIndexRoute =
  AuthenticatedPerfilIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPerfilLocacoesRoute =
  AuthenticatedPerfilLocacoesRouteImport.update({
    id: '/locacoes',
    path: '/locacoes',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)
const AuthenticatedPerfilEventosRoute =
  AuthenticatedPerfilEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLocacoesRoute =
  AuthenticatedAdminLocacoesRouteImport.update({
    id: '/locacoes',
    path: '/locacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFavoritosRoute =
  AuthenticatedAdminFavoritosRouteImport.update({
    id: '/favoritos',
    path: '/favoritos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogoRoute =
  AuthenticatedAdminCatalogoRouteImport.update({
    id: '/catalogo',
    path: '/catalogo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalendarioRoute =
  AuthenticatedAdminCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/carrinho': typeof AuthenticatedCarrinhoRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/favoritos': typeof AuthenticatedAdminFavoritosRoute
  '/admin/locacoes': typeof AuthenticatedAdminLocacoesRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/perfil/eventos': typeof AuthenticatedPerfilEventosRoute
  '/perfil/locacoes': typeof AuthenticatedPerfilLocacoesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/perfil/': typeof AuthenticatedPerfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/carrinho': typeof AuthenticatedCarrinhoRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/favoritos': typeof AuthenticatedAdminFavoritosRoute
  '/admin/locacoes': typeof AuthenticatedAdminLocacoesRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/perfil/eventos': typeof AuthenticatedPerfilEventosRoute
  '/perfil/locacoes': typeof AuthenticatedPerfilLocacoesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/perfil': typeof AuthenticatedPerfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/carrinho': typeof AuthenticatedCarrinhoRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/produto/$id': typeof ProdutoIdRoute
  '/_authenticated/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/_authenticated/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/favoritos': typeof AuthenticatedAdminFavoritosRoute
  '/_authenticated/admin/locacoes': typeof AuthenticatedAdminLocacoesRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/perfil/eventos': typeof AuthenticatedPerfilEventosRoute
  '/_authenticated/perfil/locacoes': typeof AuthenticatedPerfilLocacoesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/perfil/': typeof AuthenticatedPerfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/esqueci-senha'
    | '/redefinir-senha'
    | '/admin'
    | '/carrinho'
    | '/favoritos'
    | '/perfil'
    | '/produto/$id'
    | '/admin/calendario'
    | '/admin/catalogo'
    | '/admin/clientes'
    | '/admin/favoritos'
    | '/admin/locacoes'
    | '/admin/pedidos'
    | '/perfil/eventos'
    | '/perfil/locacoes'
    | '/admin/'
    | '/perfil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/esqueci-senha'
    | '/redefinir-senha'
    | '/carrinho'
    | '/favoritos'
    | '/produto/$id'
    | '/admin/calendario'
    | '/admin/catalogo'
    | '/admin/clientes'
    | '/admin/favoritos'
    | '/admin/locacoes'
    | '/admin/pedidos'
    | '/perfil/eventos'
    | '/perfil/locacoes'
    | '/admin'
    | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/esqueci-senha'
    | '/redefinir-senha'
    | '/_authenticated/admin'
    | '/_authenticated/carrinho'
    | '/_authenticated/favoritos'
    | '/_authenticated/perfil'
    | '/produto/$id'
    | '/_authenticated/admin/calendario'
    | '/_authenticated/admin/catalogo'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/favoritos'
    | '/_authenticated/admin/locacoes'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/perfil/eventos'
    | '/_authenticated/perfil/locacoes'
    | '/_authenticated/admin/'
    | '/_authenticated/perfil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carrinho': {
      id: '/_authenticated/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof AuthenticatedCarrinhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil/': {
      id: '/_authenticated/perfil/'
      path: '/'
      fullPath: '/perfil/'
      preLoaderRoute: typeof AuthenticatedPerfilIndexRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/perfil/locacoes': {
      id: '/_authenticated/perfil/locacoes'
      path: '/locacoes'
      fullPath: '/perfil/locacoes'
      preLoaderRoute: typeof AuthenticatedPerfilLocacoesRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/perfil/eventos': {
      id: '/_authenticated/perfil/eventos'
      path: '/eventos'
      fullPath: '/perfil/eventos'
      preLoaderRoute: typeof AuthenticatedPerfilEventosRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/locacoes': {
      id: '/_authenticated/admin/locacoes'
      path: '/locacoes'
      fullPath: '/admin/locacoes'
      preLoaderRoute: typeof AuthenticatedAdminLocacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/favoritos': {
      id: '/_authenticated/admin/favoritos'
      path: '/favoritos'
      fullPath: '/admin/favoritos'
      preLoaderRoute: typeof AuthenticatedAdminFavoritosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalogo': {
      id: '/_authenticated/admin/catalogo'
      path: '/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AuthenticatedAdminCatalogoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendario': {
      id: '/_authenticated/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AuthenticatedAdminCalendarioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCalendarioRoute: typeof AuthenticatedAdminCalendarioRoute
  AuthenticatedAdminCatalogoRoute: typeof AuthenticatedAdminCatalogoRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminFavoritosRoute: typeof AuthenticatedAdminFavoritosRoute
  AuthenticatedAdminLocacoesRoute: typeof AuthenticatedAdminLocacoesRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCalendarioRoute: AuthenticatedAdminCalendarioRoute,
  AuthenticatedAdminCatalogoRoute: AuthenticatedAdminCatalogoRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminFavoritosRoute: AuthenticatedAdminFavoritosRoute,
  AuthenticatedAdminLocacoesRoute: AuthenticatedAdminLocacoesRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPerfilRouteChildren {
  AuthenticatedPerfilEventosRoute: typeof AuthenticatedPerfilEventosRoute
  AuthenticatedPerfilLocacoesRoute: typeof AuthenticatedPerfilLocacoesRoute
  AuthenticatedPerfilIndexRoute: typeof AuthenticatedPerfilIndexRoute
}

const AuthenticatedPerfilRouteChildren: AuthenticatedPerfilRouteChildren = {
  AuthenticatedPerfilEventosRoute: AuthenticatedPerfilEventosRoute,
  AuthenticatedPerfilLocacoesRoute: AuthenticatedPerfilLocacoesRoute,
  AuthenticatedPerfilIndexRoute: AuthenticatedPerfilIndexRoute,
}

const AuthenticatedPerfilRouteWithChildren =
  AuthenticatedPerfilRoute._addFileChildren(AuthenticatedPerfilRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCarrinhoRoute: typeof AuthenticatedCarrinhoRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCarrinhoRoute: AuthenticatedCarrinhoRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
